import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Menu.module.css'

// Importing Components 
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navHolder}>
        <Navbar></Navbar>
      </div>
      <main className={styles.main}>
        <div className={styles.title}>
          <h1>Italian Resturant</h1>
          <p>Hungry? Our menu is here to the rescue.</p>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Momos</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Shandeko Momo </h4>
              <h5>Rs.170</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg chatpatey Momo </h4>
              <h5>Rs.250</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Jhaneko Momo </h4>
              <h5>Rs.170</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Jhol Momo </h4>
              <h5>Rs.170</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Chilly Momo </h4>
              <h5>Rs.170</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Fry Momo </h4>
              <h5>Rs.110</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Momo </h4>
              <h5>Rs.110</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken chatpatey Momo </h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Jhaneko Momo </h4>
              <h5>Rs.300</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Jhol Momo </h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Shandeko Momo  </h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Chilly Momo </h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Fry Momo </h4>
              <h5>Rs.140</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Momo</h4>
              <h5>Rs.140</h5>
            </div>
          </div>
          <div className={styles.c1Field1}>
            <h3>Chowmein</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Chowmein </h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Chowmein</h4>
              <h5>Rs.90</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mutton Chowmein</h4>
              <h5>Rs.190</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Egg Chowmein</h4>
              <h5>Rs.110</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mixed Chowmein</h4>
              <h5>Rs.140</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Buff Chowmein</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Expresso Based Drinks</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Ristertto</h4>
              <h5>Rs.85</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Expresso</h4>
              <h5>Rs.85</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Expresso Lungo</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Dippio</h4>
              <h5>Rs.110</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Afugato</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Americano</h4>
              <h5>Rs.110</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Americano Double Shot</h4>
              <h5>Rs.160</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Americano Royal </h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cappuccino</h4>
              <h5>Rs.140</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cafe Latte</h4>
              <h5>Rs.140</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cafe Mocha(mochhaccino)</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Caremell Latte</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Honey Latte </h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mocha Madness</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Flavour On Coffee</h4>
              <h5>Rs.40</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Candel</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Spray</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Spl Coupleccino</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Spl Babyccino</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Blended Vinalla Mocha</h4>
              <h5>Rs.230</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Italian Special Cold Coffee</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Italian Special Oreoccino</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Double Shot Cappuccino</h4>
              <h5>Rs.180</h5>
            </div>
          </div>
          <div className={styles.c1Field1}>
            <h3>Coffee Alternative</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Milk Tea</h4>
              <h5>Rs.50</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Black Tea</h4>
              <h5>Rs.40</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Lemon Tea</h4>
              <h5>Rs.50</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Hot Lemon</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Green Tea</h4>
              <h5>Rs.120</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Hot Chocolate</h4>
              <h5>Rs.160</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Hot Lemon Honey</h4>
              <h5>Rs.120</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Ballon</h4>
              <h5>Rs.130</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Pizza</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Cheese Pizza Small</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cheese Pizza Large</h4>
              <h5>Rs.520</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Pizza Small</h4>
              <h5>Rs.240</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Pizza Large</h4>
              <h5>Rs.540</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Pizza small</h4>
              <h5>Rs.360</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Pizza Large</h4>
              <h5>Rs.630</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mushroom Pizza Small</h4>
              <h5>Rs.260</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mushroom Pizza Large</h4>
              <h5>Rs.580</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Special Pizza Small</h4>
              <h5>Rs.360</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Special Pizza Large</h4>
              <h5>Rs.750</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sausage Pizza Small</h4>
              <h5>Rs.250</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sausage Pizza Large</h4>
              <h5>Rs.580</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cheese Topping</h4>
              <h5>Rs.50</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Delight Pizza Small</h4>
              <h5>Rs.300</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Delight Pizza Large</h4>
              <h5>Rs.680</h5>
            </div>
          </div>
          <div className={styles.c1Field1}>
            <h3>Burger</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Burger</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Burger</h4>
              <h5>Rs.130</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Hot Zinger</h4>
              <h5>Rs.160</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Add on Cheese</h4>
              <h5>Rs.40</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Iced Beverages</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Iced Cappuccino</h4>
              <h5>Rs.170</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Iced Americano</h4>
              <h5>Rs.140</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Iced Mocha</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Iced Caramel Latte</h4>
              <h5>Rs.190</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Special Cold Coffee</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Bourboun Cone (110ml)</h4>
              <h5>Rs.125</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Choco Vanilla(Cone) 70ml</h4>
              <h5>Rs.75</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Choco Vanilla(bar) 60ml</h4>
              <h5>Rs.80</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Choco Baby(35ml)</h4>
              <h5>Rs.40</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Strawberry Cup</h4>
              <h5>Rs.40</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Butter Scotch(90ml)</h4>
              <h5>Rs.65</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cappuccino Truffle(100ml)</h4>
              <h5>Rs.125</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chocolate Cone(100ml)</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Butter Scotch Cone(100ml)</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Vanilla(cup)</h4>
              <h5>Rs.40</h5>
            </div>
          </div>
          <div className={styles.c1Field1}>
            <h3>Blended Coffee</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Blended Mocha</h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Blended Vanilla Mocha</h4>
              <h5>Rs.230</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Caramel Machiato</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Special Oreoccino</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Blended Caramel Machiato</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Shakes & Smoothies</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Icecream Shake Vanilla</h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Icecream Shake Chocolate</h4>
              <h5>Rs.210</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Oreo Shake</h4>
              <h5>Rs.230</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Kitkat Shake</h4>
              <h5>Rs.230</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mango Smoothie</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>kiwi Smoothie</h4>
              <h5>Rs.240</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Strawberry Smoothie</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Banana Smoothie</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Milk Shake</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Blue Angel</h4>
              <h5>Rs.250</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Banana Lassi</h4>
              <h5>Rs.130</h5>
            </div>
            <span></span>
          </div>
          <div className={styles.c1Field1}>
            <h3>Refreshners</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Virgin Mojito</h4>
              <h5>Rs.190</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Blue Ocean</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Ice Lemonade</h4>
              <h5>Rs.160</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Blended Lemonade</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Lemon sprite</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Fresh Lime</h4>
              <h5>Rs.70</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Peach Iced Tea</h4>
              <h5>Rs.160</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cold Drink 500ml</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mint Lemonade</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Watermelon Mojito</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Red Bull</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Masala Coke</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Lemon Iced Tea</h4>
              <h5>Rs.160</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Strawberry Mojito</h4>
              <h5>Rs.230</h5>
            </div>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Fried Chicken</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Leg Piece</h4>
              <h5>Rs.120</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Wings</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Lolipop 2pcs</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Stick</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Popcron</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Stripes</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sausage Fried</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sausage Boiled</h4>
              <h5>Rs.150</h5>
            </div>
          </div>
          <div className={styles.c1Field1}>
            <h3>Breakfast</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>American Breakfast</h4>
              <h5>Rs.250</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Western Breakfast</h4>
              <h5>Rs.350</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Muesli</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Masala Omlet</h4>
              <h5>Rs.80</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Toasted Bread</h4>
              <h5>Rs.30</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Cold Drink</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Cold Drink</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Juice</h4>
              <h5>Rs.40</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Coke</h4>
              <h5>Rs.70</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Fanta</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Slice</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mountain Dew</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>7ups</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Pepsi</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sprite</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Water</h4>
              <h5>Rs.40</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Coke 1.5ltr</h4>
              <h5>Rs.220</h5>
            </div>
            <span></span>
          </div>
          <div className={styles.c1Field1}>
            <h3>Soups</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Manchow Soup</h4>
              <h5>Rs.110</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Monchow Soup</h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Hot & Sour Veg Soup</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Hot & Sour Chicken soup</h4>
              <h5>Rs.140</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken clear Soup</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Icecream</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Vanilla Scoop</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chocolate Scoop</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Strawberry Scoop</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>21st Love Scoop</h4>
              <h5>Rs.60</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sundae Cup</h4>
              <h5>Rs.80</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Fantasy 200</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Choco Browine </h4>
              <h5>Rs.150</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Browines Sundae</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sunday Cup</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
          </div>
          <div className={styles.c1Field1}>
            <h3>Bakery</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Pastry White</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Birthday Cake Vanilla</h4>
              <h5>Rs.700</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Birthday Cake Chocolate</h4>
              <h5>Rs.750</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Birthday Cake Forest</h4>
              <h5>Rs.800</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Birthday Cake Forest</h4>
              <h5>Rs.800</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Pastry Black</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Chilly</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Chilly</h4>
              <h5>Rs.280</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mushroom Chilly</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Drums Of Heaven</h4>
              <h5>Rs.300</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Sausage Chilly</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Shandeko</h4>
              <h5>Rs.280</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Choila</h4>
              <h5>Rs.300</h5>
            </div>
            <span></span>
          </div>
          <div className={styles.c1Field1}>
            <h3>Veg Appetizer</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Aalo Shandeko</h4>
              <h5>Rs.120</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>French Fries</h4>
              <h5>Rs.140</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chips Chilly</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Pepper Corn Chilly</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Stripes</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>WaiWai Shandeko</h4>
              <h5>Rs.100</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Honey Chilly Potato</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Clear Soup</h4>
              <h5>Rs.80</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Potato  Wedges</h4>
              <h5>Rs.160</h5>
            </div>
            <span></span>
          </div>
        </div>
        <div className={styles.c1Field}>
          <div className={styles.c1Field1}>
            <h3>Hookah</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Hookah</h4>
              <h5>Rs.350</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Add on Flavour</h4>
              <h5>Rs.200</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Add on Charcoal</h4>
              <h5>Rs.30</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Cigratte</h4>
              <h5>Rs.30</h5>
            </div>
          </div>
          <div className={styles.c1Field1}>
            <h3>Thukpa</h3>
            <span></span>
            <div className={styles.menus}>
              <h4>Veg Thukpa</h4>
              <h5>Rs.130</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Chicken Thukpa</h4>
              <h5>Rs.180</h5>
            </div>
            <span></span>
            <div className={styles.menus}>
              <h4>Mix Thukpa</h4>
              <h5>Rs.220</h5>
            </div>
          </div>
        </div>
      </main>
      <Footer></Footer>
    </>
  )
}